apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timeseries-deployment
  labels:
    app: timeseries
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timeseries
    spec:
      containers:
      - image: rethinkdb:2.3.5
        name: rethinkdb
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 5672
          name: db
