# Each image will run as a service in a container
#
# This file defines all the services we want to use along with details about how and where those services will run
#
# This file will be used by Docker Compose (version 3)
# 


version: "3"

services:

  ase_compute:
    build: ./_base
    container_name: ase_compute
    ports:
      - "5000:8080"
    volumes:
      - ./ase_compute:/go/src/ase_compute
    working_dir: /go/src/ase_compute
    links:
      # connect using host="ase_timeseries"
      - ase_timeseries


  ase_timeseries:
    image: mongo:3.4
    container_name: ase_timeseries
    ports:
      - "27017:27017"
    volumes:
      - ./ase_timeseries/mongodb:/data/db


  ase_twitter:
    build: ./_base
    container_name: ase_twitter
    ports:
      - "5001:8080"
    volumes:
      - ./ase_twitter:/go/src/ase_twitter
    working_dir: /go/src/ase_twitter
