# Each image will run as a service in a container
#
# This file defines all the services we want to use along with details about how and where those services will run
#
# This file will be used by Docker Compose (version 3)
#


version: "3"

services:

  api:
    build:
      context: ./
      dockerfile: ase_api_Dockerfile
    ports:
      - "8000:8000"
    links:
      - timeseries-db # register new terms
      - queue # load generation


  compute:
    build:
      context: ./
      dockerfile: ase_compute_Dockerfile
    links:
      - timeseries-db # fetch terms and update sentiment
      - queue # fetch tweets to process


  queue:
    # https://hub.docker.com/_/rabbitmq/
    image: rabbitmq:3.6.9-alpine
    container_name: queue
    ports:
      - "5672:5672"


  timeseries-db:
    # https://hub.docker.com/_/rethinkdb/
    image: rethinkdb:2.3.5
    ports:
      - "28015:28015"
      - "8080:8080" # Admin interface


  twitter:
    build:
      context: ./
      dockerfile: ase_twitter_Dockerfile
    links:
      - timeseries-db # fetch terms
      - queue # add tweets


  web:
    build: ase_web
    ports:
      - "80:8080"
    links:
      - timeseries-db # API calls
