# Each image will run as a service in a container
#
# This file defines all the services we want to use along with details about how and where those services will run
#
# This file will be used by Docker Compose (version 3)
#


version: "3"

services:

  ase_api:
    build: ./_base
    container_name: ase_api
    ports:
      - "5002:8000"
    volumes:
      - ./ase_api:/go/src/ase_api
    working_dir: /go/src/ase_api
    links:
      # register new terms
      - ase_timeseries
      # load generation
      - ase_queue


  ase_compute:
    build: ./_base
    container_name: ase_compute
    ports:
      - "5000:8080"
    volumes:
      - ./ase_compute:/go/src/ase_compute
    working_dir: /go/src/ase_compute
    links:
      # fetch terms and update sentiment
      - ase_timeseries
      # fetch tweets to process
      - ase_queue


  ase_queue:
    # https://hub.docker.com/_/rabbitmq/
    image: rabbitmq:3.6.9-alpine
    container_name: ase_queue
    ports:
      - "5672:5672"


  ase_timeseries:
    # https://hub.docker.com/_/rethinkdb/
    image: rethinkdb:2.3.5
    container_name: ase_timeseries
    ports:
      - "28015:28015"
      - "5010:8080" # Admin interface
    # volumes: # make sure this exists locally
    #   - ./ase_timeseries/mongodb:/data/db


  ase_twitter:
    build: ./_base
    container_name: ase_twitter
    ports:
      - "5001:8080"
    volumes:
      - ./ase_twitter:/go/src/ase_twitter
    working_dir: /go/src/ase_twitter
    links:
      # fetch terms
      - ase_timeseries
      # add tweets
      - ase_queue
