# Each image will run as a service in a container
#
# This file defines all the services we want to use along with details about how and where those services will run
#
# This file will be used by Docker Compose (version 3)
# 


version: "3"

services:

  compute:
    build: ./_base
    container_name: ase_compute
    ports:
      - "5000:8080"
    volumes:
      - ./compute:/go/src/ase_compute
    working_dir: /go/src/ase_compute
