apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: advse17
    spec:
      containers:
      - name: api
        image: eu.gcr.io/advse-167708/ase_api
        ports:
        - containerPort: 8000
          name: http
