apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
      - name: twitter
        image: eu.gcr.io/advse-167708/ase_twitter
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"
