apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
      - name: twitter
        image: eu.gcr.io/advse-167708/ase_twitter
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
