apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compute-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: advse17
    spec:
      containers:
      - name: compute
        image: eu.gcr.io/advse-167708/ase_compute
