apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compute-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: compute
    spec:
      containers:
      - name: compute
        image: eu.gcr.io/advse-167708/ase_compute
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"
