apiVersion: v1
kind: Service
metadata:
  name: queue_broker
  labels:
    app: queue_broker
spec:
  type: NodePort
  ports:
  - port: 5672
    name: main-port
    nodePort: 30672
  - port: 15672
    name: admin-port
    nodePort: 30080
  selector:
    app: queue_broker
