apiVersion: v1
kind: Service
metadata:
  name: timeseries-admin
  labels:
    app: timeseries
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: admin-port
    nodePort: 30088
  selector:
    app: timeseries
