apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweets-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweets
    spec:
      containers:
      - name: tweets
        image: eu.gcr.io/advse-167708/ase_load_tweets
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"
        ports:
        - containerPort: 27017
          name: db
