# We use this stack file instead of Dockerfiles
# to specify images
#
# Each image will run as a service in a container
#
# This file defines all the services we want to use along with details about how and where those services will run
#
# This file will be used by Docker Compose (version 3)
# 
# $GOPATH needs to be defined or your local machine
#
# 


version: "3"

services:

  compute:
    image: golang:1.8
    ports:
      - 8080:8080
    volumes:
      - ./compute:/go/src/compute
      # - $GOPATH/src/github.com/arddor/advse17:
    working_dir: /go/src/compute
    command:
      - go get -d
      - go run main.go
    # links:
    #     - redis
    #     
    # redis:
    #   image: redis:alpine
