apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.9-alpine
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
          limits:
            memory: "4096Mi"
            cpu: "400m"
        ports:
        - containerPort: 5672
          name: q
