apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: advse17
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.9-alpine
        ports:
        - containerPort: 5672
          name: q
