apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: queue
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    name: main-port
    nodePort: 30672
  - port: 15672
    name: admin-port
    nodePort: 30080
  selector:
    app: queue
