apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HIPE_COMPILE
          value: "1"
        resources:
          requests:
            memory: "4096Mi"
            cpu: "500m"
          limits:
            memory: "8192Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5672
          hostPort: 5672
        - containerPort: 15672
          hostPort: 15672
